export const initialBookState = {
  id: '',
  image: '',
  category: '',
  options: '',
  title: '',
  author: '',
  publishedby: '',
  year: '',
  genre: '',
  format: '',
  language: '',
  price: '',
  currency: 'USD',
  stock: '',
  condition: '',
  seller: '',
  location: '',
  description: '',
  views: '',
  genres: [],
  formats: [],
  languages: []
};

export const initialMapState = {
  id: '',
  image: '',
  category: 'maps',
  options: '',
  title: '',
  price: '',
  currency: 'USD',
  stock: '',
  condition: '',
  year: '',
  color: '',
  size: '',
  seller: '',
  location: '',
  description: '',
  views: '',
  colors: [],
  sizes: []
};
